TYPO3:
  CMS:
    Form:

      mixins:
        formElementMixins:
          CaptchaMixin:
            __inheritances:
              10: 'TYPO3.CMS.Form.mixins.formElementMixins.FormElementMixin'

      prototypes:
        standard:
          formEditor:
            dynamicRequireJsModules:
              additionalViewModelModules:
                1623227656: 'TYPO3/CMS/BwCaptcha/Backend/FormEditor/CaptchaViewModel'
            formEditorPartials:
              FormElement-Captcha: 'Stage/SimpleTemplate'

          formElementsDefinition:
            Form:
              renderingOptions:
                translation:
                  translationFiles:
                    10: 'EXT:bw_captcha/Resources/Private/Language/locallang.xlf'
                partialRootPaths:
                  1623227656: 'EXT:bw_captcha/Resources/Private/Frontend/Partials/'
                templateRootPaths:
                  1623227656: 'EXT:bw_captcha/Resources/Private/Frontend/Templates/'

            Captcha:
              implementationClassName: 'Blueways\BwCaptcha\Domain\Model\FormElements\CaptchaElement'
              formEditor:
                label: formEditor.elements.Captcha
                group: custom
                groupSorting: 1000
                iconIdentifier: 't3-form-captcha-element'

          validatorsDefinition:
            Captcha:
              implementationClassName: 'Blueways\BwCaptcha\Validation\Validator\CaptchaValidator'
              options:
                phrase: ''
